services:
  - type: worker
    name: middleman-bot
    plan: starter
    runtime: docker
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BLOCKCYPHER_TOKEN
        sync: false
      - key: CMC_API_KEY
        sync: false
      - key: LOGSNAG_API_KEY
        sync: false
      - key: TOS_CHANNEL_ID
        sync: false
      - key: VOUCH_CHANNEL_ID
        sync: false
      - key: SUPPORT_ROLE_ID
        sync: false
      - key: CLIENT_ROLE_ID
        sync: false
      - key: TOP_CLIENT_ROLE_ID
        sync: false
      - key: RICH_CLIENT_ROLE_ID
        sync: false
      - key: PREMIER_CLIENT_ROLE_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: middleman-db
          property: connectionString
databases:
  - name: middleman-db
    plan: starter
    region: oregon
    databaseName: middleman
