services:
  - type: worker
    name: middleman-bot
    plan: starter
    runtime: docker
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BLOCKCYPHER_TOKEN
        sync: false
      - key: CMC_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: middleman-db
          property: connectionString
databases:
  - name: middleman-db
    plan: starter
    region: oregon
    databaseName: middleman
