/* eslint-disable @typescript-eslint/naming-convention */

export enum EMOJIS {
  LOADING = '<a:loading:1137863799865610343>',
  BITCOIN = '<:btc:1137863907038470254>',
  ETHEREUM = '<:eth:1137863804009599117>',
  LITECOIN = '<:ltc:1137863885337133076>',
  CASHAPP = '<:cashapp:1137901857155596308>',
}

export enum PARTIES {
  SENDER = 'SENDER',
  RECEIVER = 'RECEIVER',
}

export enum COLORS {
  MAIM = '#ADD8E6',
  ERROR = 'RED',
  SUCCESS = 'GREEN',
  WARNING = 'YELLOW',
}

export const RESPONSES = {
  SIMPLE: { CONFIRM: 'Yes', DENY: 'No' },
};

export enum TRADE_EVENTS {
  TERMINATED,
  ITEMS_SECURED,
}

export enum TRADE_TYPES {
  LIMITEDS = 'LIMITEDS',
  ETHEREUM = 'ETH',
  BITCOIN = 'BTC',
  LITECOIN = 'LTC',
  CRYPTO = 'CRYPTO',
  ADOPT_ME = 'ADOPT_ME',
  HOOD_MODDED = 'HOOD_MODDED',
}

export type CRYPTO_TRADE_TYPES = TRADE_TYPES.ETHEREUM | TRADE_TYPES.BITCOIN | TRADE_TYPES.LITECOIN;
export type GAME_TRADE_TYPES = TRADE_TYPES.ADOPT_ME | TRADE_TYPES.HOOD_MODDED;

export const EXPANDED_TRADE_TYPES = {
  [TRADE_TYPES.LIMITEDS]: 'Limiteds',
  [TRADE_TYPES.ETHEREUM]: 'Ethereum',
  [TRADE_TYPES.BITCOIN]: 'Bitcoin',
  [TRADE_TYPES.LITECOIN]: 'Litecoin',
  [TRADE_TYPES.ADOPT_ME]: 'Pets',
  [TRADE_TYPES.HOOD_MODDED]: 'Items',
};

export const CRYPTO_CONFIRMATIONS = {
  [TRADE_TYPES.BITCOIN]: 1,
  [TRADE_TYPES.ETHEREUM]: 12,
  [TRADE_TYPES.LITECOIN]: 2,
};

export enum INTERACTIONS {
  PARTY_IDENTIFICATION_SENDING_BUTTON = 'PARTY_IDENTIFICATION_SENDING_BUTTON',
  PARTY_IDENTIFICATION_RECEIVING_BUTTON = 'PARTY_IDENTIFICATION_RECEIVING_BUTTON',
  PARTY_IDENTIFICATION_RESET_BUTTON = 'PARTY_IDENTIFICATION_RESET_BUTTON',
  DEAL_CANCEL_RETURN_BUTTON = 'DEAL_CANCEL_RETURN_BUTTON',
  CRYPTO_PASTE_ITEMS_BUTTON = 'CRYPTO_PASTE_ITEMS_BUTTON',
  CHANGE_ACCOUNT_BUTTON = 'CHANGE_ACCOUNT_BUTTON',
  CONFIRMATIONS_CONFIRM_BUTTON = 'CONFIRMATIONS_CONFIRM_BUTTON',
  CONFIRMATIONS_DENY_BUTTON = 'CONFIRMATIONS_CANCEL_BUTTON',
  SEND_TRADE_BACK_BUTTON = 'SEND_TRADE_BACK_BUTTON',
  LIMITEDS_QUEUE_CANCEL_BUTTON = 'LIMITEDS_QUEUE_CANCEL_BUTTON',
  CRYPTO_COIN_SELECTION_MENU = 'CRYPTO_COIN_SELECTION_MENU',
  TRADE_CANCELATION_RETURN_TO_MENU = 'TRADE_CANCELATION_RETURN_TO_MENU',
  TWO_FACTOR_MODAL = 'TWO_FACTOR_MODAL',
  DELETE_TWO_FACTOR_MODAL = 'DELETE_TWO_FACTOR_MODAL',
  TWO_FACTOR_MODAL_CODE_INPUT = 'TWO_FACTOR_MODAL_CODE_INPUT',
  VERIFY_IDENTITY_MODAL = 'VERIFY_IDENTITY_MODAL',
  FRIEND_COMMAND_RESEND_BUTTON = 'FRIEND_COMMAND_RESEND_REQUEST',
  FRIEND_COMMAND_RETRY_BUTTON = 'FRIEND_COMMAND_RETRY_REQUEST',
  TICKET_CLOSE_BUTTON = 'TICKET_CLOSE_BUTTON',
  CRYPTO_RELEASE_RETRY_BUTTON = 'CRYPTO_RELEASE_RETRY_BUTTON',
  FEE_PAYMENT_METHOD_SELECTION_MENU = 'FEE_PAYMENT_METHOD_SELECTION_MENU',
}

export const REPLY_DELETE_TIMEOUT = 2000;

export const PLACE_IDS = {
  [TRADE_TYPES.ADOPT_ME]: '920587237',
  [TRADE_TYPES.HOOD_MODDED]: '5602055394',
};

export enum GAME_TRADE_STATUSES {
  WAITING_FOR_SENDER = 'WAITING_FOR_SENDER',
  READY_TO_TRADE = 'READY_TO_TRADE',
  WAITING_FOR_RELEASE = 'WAITING_FOR_RELEASE',
  DEAL_RELEASED = 'DEAL_RELEASED',
  DEAL_REDEEMED = 'DEAL_REDEEMED',
}

export enum PAYMENT_METHODS {
  CASHAPP = 'CASHAPP',
  ETHEREUM = 'ETH',
  BITCOIN = 'BTC',
  LITECOIN = 'LTC',
}
